<a href="https://colab.research.google.com/github/manojgundumogula55-commits/Digital-Library-Usage-And-Resource-Analytics/blob/main/Data_Loading_and_Reading.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# 📥 Data Loading & Reading
## Importing Pandas Library

In [5]:
import pandas as pd

In [23]:
## 1. Loading the Dataset

In [6]:
from google.colab import files

uploaded = files.upload()
file_path = next(iter(uploaded))

df = pd.read_csv(file_path)
df

Saving library_usage_raw.csv to library_usage_raw (2).csv

,access_id,user_id,user_type,department,resource_id,resource_title,resource_type,publisher,publication_year,access_datetime,session_minutes,device,downloaded,rating,access_mode
0,A00001,U1675,Undergraduate,Mechanical,R070,SpringerLink Vol.1,Database,IEEE,2015,2025-03-19 23:30:00,33.6,Laptop,0,4.0,Remote
1,A00002,U1448,Undergraduate,ECE,R068,PhD Thesis Vol.3,Thesis,Wiley,2008,2025-03-26 14:18:00,26.9,Laptop,1,4.0,Remote
2,A00003,U1015,Faculty,Civil,R023,Finance Vol.2,Journal,Pearson,2005,2025-01-27 07:54:00,60.3,Campus PC,0,5.0,Remote
3,A00004,U1124,Undergraduate,Sciences,R049,Finance Vol.2,Journal,NPTEL,2011,2025-12-16 12:39:00,42.0,Laptop,1,2.0,On-Campus
4,A00005,U1298,Postgraduate,Sciences,R056,Signal Processing Vol.5,Journal,Wiley,2021,2025-09-20 11:53:00,8.0,Laptop,0,4.0,Remote
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1495,A01496,U1038,Faculty,Management,R067,Data Science Vol.2,E-Book,NPTEL,2021,2025-02-14 21:40:00,10.8,Campus PC,0,4.0,On-Campus
1496,A01497,U1055,Researcher,CSE,R070,SpringerLink Vol.1,Database,IEEE,2015,2025-11-02 21:05:00,25.7,Mobile,0,5.0,On-Campus
1497,A01498,U1003,Undergraduate,Management,R021,JSTOR Vol.3,Database,Taylor & Francis,2016,2025-04-28 09:50:00,49.8,Laptop,1,5.0,On-Campus
1498,A01499,U1399,Postgraduate,Civil,R049,Finance Vol.2,Journal,NPTEL,2011,2025-04-14 14:29:00,44.4,Laptop,0,5.0,On-Campus
1499,A01500,U1040,Postgraduate,Sciences,R067,Data Science Vol.2,E-Book,NPTEL,2021,2025-04-28 19:33:00,114.5,Laptop,1,4.0,On-Campus

In [8]:
## 2. Displaying the First Five Records

In [9]:
df.head()

,access_id,user_id,user_type,department,resource_id,resource_title,resource_type,publisher,publication_year,access_datetime,session_minutes,device,downloaded,rating,access_mode
0,A00001,U1675,Undergraduate,Mechanical,R070,SpringerLink Vol.1,Database,IEEE,2015,2025-03-19 23:30:00,33.6,Laptop,0,4.0,Remote
1,A00002,U1448,Undergraduate,ECE,R068,PhD Thesis Vol.3,Thesis,Wiley,2008,2025-03-26 14:18:00,26.9,Laptop,1,4.0,Remote
2,A00003,U1015,Faculty,Civil,R023,Finance Vol.2,Journal,Pearson,2005,2025-01-27 07:54:00,60.3,Campus PC,0,5.0,Remote
3,A00004,U1124,Undergraduate,Sciences,R049,Finance Vol.2,Journal,NPTEL,2011,2025-12-16 12:39:00,42.0,Laptop,1,2.0,On-Campus
4,A00005,U1298,Postgraduate,Sciences,R056,Signal Processing Vol.5,Journal,Wiley,2021,2025-09-20 11:53:00,8.0,Laptop,0,4.0,Remote

In [7]:
## 3. Displaying the Last Five Records

In [10]:
df.tail()

,access_id,user_id,user_type,department,resource_id,resource_title,resource_type,publisher,publication_year,access_datetime,session_minutes,device,downloaded,rating,access_mode
1495,A01496,U1038,Faculty,Management,R067,Data Science Vol.2,E-Book,NPTEL,2021,2025-02-14 21:40:00,10.8,Campus PC,0,4.0,On-Campus
1496,A01497,U1055,Researcher,CSE,R070,SpringerLink Vol.1,Database,IEEE,2015,2025-11-02 21:05:00,25.7,Mobile,0,5.0,On-Campus
1497,A01498,U1003,Undergraduate,Management,R021,JSTOR Vol.3,Database,Taylor & Francis,2016,2025-04-28 09:50:00,49.8,Laptop,1,5.0,On-Campus
1498,A01499,U1399,Postgraduate,Civil,R049,Finance Vol.2,Journal,NPTEL,2011,2025-04-14 14:29:00,44.4,Laptop,0,5.0,On-Campus
1499,A01500,U1040,Postgraduate,Sciences,R067,Data Science Vol.2,E-Book,NPTEL,2021,2025-04-28 19:33:00,114.5,Laptop,1,4.0,On-Campus

In [11]:
## 4. Checking Dataset Dimensions

In [12]:
print("Number of Rows:", df.shape[0])
print("Number of Columns:", df.shape[1])

Number of Rows: 1500
Number of Columns: 15

In [24]:
## 5. Displaying Dataset Column Names

In [13]:
print(df.columns)

Index(['access_id', 'user_id', 'user_type', 'department', 'resource_id',
       'resource_title', 'resource_type', 'publisher', 'publication_year',
       'access_datetime', 'session_minutes', 'device', 'downloaded', 'rating',
       'access_mode'],
      dtype='object')

In [25]:
## 6. Checking Data Types of Columns

In [14]:
df.dtypes

access_id            object
user_id              object
user_type            object
department           object
resource_id          object
resource_title       object
resource_type        object
publisher            object
publication_year      int64
access_datetime      object
session_minutes     float64
device               object
downloaded            int64
rating              float64
access_mode          object
dtype: object

In [26]:
## 7. Inspecting Dataset Information

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1500 entries, 0 to 1499
Data columns (total 15 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   access_id         1500 non-null   object
 1   user_id           1500 non-null   object
 2   user_type         1500 non-null   object
 3   department        1500 non-null   object
 4   resource_id       1500 non-null   object
 5   resource_title    1500 non-null   object
 6   resource_type     1500 non-null   object
 7   publisher         1484 non-null   object
 8   publication_year  1500 non-null   int64
 9   access_datetime   1500 non-null   object
 10  session_minutes   1433 non-null   float64
 11  device            1479 non-null   object
 12  downloaded        1500 non-null   int64
 13  rating            1411 non-null   float64
 14  access_mode       1500 non-null   object
dtypes: float64(2), int64(2), object(11)
memory usage: 175.9+ KB

In [17]:
## 8. Generating Descriptive Statistics

In [16]:
df.describe()

       publication_year  session_minutes   downloaded       rating
count       1500.000000      1433.000000  1500.000000  1411.000000
mean        2014.882667        39.511235     0.329333     3.768249
std            5.536907       100.822327     0.470128     1.129620
min         2005.000000        -5.000000     0.000000     1.000000
25%         2010.000000        15.000000     0.000000     3.000000
50%         2015.000000        26.000000     0.000000     4.000000
75%         2020.000000        39.400000     1.000000     5.000000
max         2025.000000       999.000000     1.000000     5.000000

In [27]:
# 🔎 Data Acquisition & Filtering

In [28]:
## 1. Analyzing Resource Type Categories

In [18]:
df["resource_type"].unique()
print(df["resource_type"].value_counts())

resource_type
E-Book      549
Database    400
Journal     392
Thesis      127
Video        32
Name: count, dtype: int64

In [29]:
## 2. Exploring User Type Categories

In [19]:
df["user_type"].unique()
print(df["user_type"].value_counts())

user_type
Undergraduate    793
Postgraduate     370
Faculty          174
Researcher       137
UNDERGRADUATE     15
POSTGRADUATE       6
FACULTY            4
RESEARCHER         1
Name: count, dtype: int64

In [30]:
## 3. Examining Usage Across Departments

In [20]:
df["department"].unique()
print(df["department"].value_counts())

department
CSE           265
Mechanical    250
ECE           249
Management    242
Civil         224
Sciences      220
 cse           29
ece            21
Name: count, dtype: int64

In [31]:
## 4. Assessing Access Mode and Device Categories

In [21]:
df["access_mode"].unique()
print(df["access_mode"].value_counts())

df["device"].unique()
print(df["device"].value_counts())

access_mode
On-Campus    891
Remote       609
Name: count, dtype: int64
device
Laptop       672
Mobile       543
Campus PC    264
Name: count, dtype: int64

In [32]:
## 5. Selecting Required Columns

In [33]:
selected_data = df[
    [
        "access_id",
        "user_id",
        "user_type",
        "department",
        "resource_id",
        "resource_title",
        "resource_type",
        "publisher",
        "access_datetime",
        "session_minutes",
        "device",
        "downloaded",
        "rating",
        "access_mode",
    ]
]
display(selected_data.head())

,access_id,user_id,user_type,department,resource_id,resource_title,resource_type,publisher,access_datetime,session_minutes,device,downloaded,rating,access_mode
0,A00001,U1675,Undergraduate,Mechanical,R070,SpringerLink Vol.1,Database,IEEE,2025-03-19 23:30:00,33.6,Laptop,0,4.0,Remote
1,A00002,U1448,Undergraduate,ECE,R068,PhD Thesis Vol.3,Thesis,Wiley,2025-03-26 14:18:00,26.9,Laptop,1,4.0,Remote
2,A00003,U1015,Faculty,Civil,R023,Finance Vol.2,Journal,Pearson,2025-01-27 07:54:00,60.3,Campus PC,0,5.0,Remote
3,A00004,U1124,Undergraduate,Sciences,R049,Finance Vol.2,Journal,NPTEL,2025-12-16 12:39:00,42.0,Laptop,1,2.0,On-Campus
4,A00005,U1298,Postgraduate,Sciences,R056,Signal Processing Vol.5,Journal,Wiley,2025-09-20 11:53:00,8.0,Laptop,0,4.0,Remote

In [34]:
## 6. Filtering Downloaded Resources

In [22]:
downloaded_cases = df[df["downloaded"] == 1]
display(downloaded_cases)
print("Number of downloads: ", downloaded_cases.shape)

,access_id,user_id,user_type,department,resource_id,resource_title,resource_type,publisher,publication_year,access_datetime,session_minutes,device,downloaded,rating,access_mode
1,A00002,U1448,Undergraduate,ECE,R068,PhD Thesis Vol.3,Thesis,Wiley,2008,2025-03-26 14:18:00,26.9,Laptop,1,4.0,Remote
3,A00004,U1124,Undergraduate,Sciences,R049,Finance Vol.2,Journal,NPTEL,2011,2025-12-16 12:39:00,42.0,Laptop,1,2.0,On-Campus
5,A00006,U1026,Faculty,Mechanical,R070,SpringerLink Vol.1,Database,IEEE,2015,2025-09-26 01:14:00,12.1,Campus PC,1,2.0,Remote
6,A00007,U1117,Postgraduate,CSE,R055,Data Science Vol.1,E-Book,Springer,2016,2025-10-23 08:50:00,37.2,Laptop,1,5.0,On-Campus
7,A00008,U1554,Undergraduate,Sciences,R038,Marketing Vol.2,E-Book,Taylor & Francis,2017,2025-08-09 14:19:00,10.5,NaN,1,4.0,Remote
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1485,A01486,U1192,Undergraduate,Civil,R006,Programming Vol.3,E-Book,NPTEL,2006,2025-10-17 09:49:00,20.9,Laptop,1,4.0,On-Campus
1488,A01489,U1697,Undergraduate,Management,R003,JSTOR Vol.4,Database,Pearson,2007,2025-09-01 16:26:00,7.9,Mobile,1,3.0,On-Campus
1493,A01494,U1418,Postgraduate,Mechanical,R024,Chemistry Vol.2,Journal,IEEE,2013,2025-02-07 13:25:00,999.0,Mobile,1,1.0,On-Campus
1497,A01498,U1003,Undergraduate,Management,R021,JSTOR Vol.3,Database,Taylor & Francis,2016,2025-04-28 09:50:00,49.8,Laptop,1,5.0,On-Campus
1499,A01500,U1040,Postgraduate,Sciences,R067,Data Science Vol.2,E-Book,NPTEL,2021,2025-04-28 19:33:00,114.5,Laptop,1,4.0,On-Campus

Number of downloads:  (494, 15)

In [35]:
## 7. Filtering Remote Access Cases

In [36]:
remote_cases = df[df["access_mode"] == "Remote"]
display(remote_cases)
print("Shape of Remote Cases:", remote_cases.shape)

,access_id,user_id,user_type,department,resource_id,resource_title,resource_type,publisher,publication_year,access_datetime,session_minutes,device,downloaded,rating,access_mode
0,A00001,U1675,Undergraduate,Mechanical,R070,SpringerLink Vol.1,Database,IEEE,2015,2025-03-19 23:30:00,33.6,Laptop,0,4.0,Remote
1,A00002,U1448,Undergraduate,ECE,R068,PhD Thesis Vol.3,Thesis,Wiley,2008,2025-03-26 14:18:00,26.9,Laptop,1,4.0,Remote
2,A00003,U1015,Faculty,Civil,R023,Finance Vol.2,Journal,Pearson,2005,2025-01-27 07:54:00,60.3,Campus PC,0,5.0,Remote
4,A00005,U1298,Postgraduate,Sciences,R056,Signal Processing Vol.5,Journal,Wiley,2021,2025-09-20 11:53:00,8.0,Laptop,0,4.0,Remote
5,A00006,U1026,Faculty,Mechanical,R070,SpringerLink Vol.1,Database,IEEE,2015,2025-09-26 01:14:00,12.1,Campus PC,1,2.0,Remote
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1484,A01485,U1399,Undergraduate,Management,R044,Finance Vol.1,Journal,IEEE,2024,2025-02-02 18:57:00,12.8,Mobile,0,4.0,Remote
1486,A01487,U1271,Postgraduate,Management,R036,JSTOR Vol.3,Database,McGraw Hill,2010,2025-09-06 10:49:00,9.7,Mobile,0,4.0,Remote
1490,A01491,U1688,Undergraduate,ECE,R075,ScienceDirect Vol.5,Database,Pearson,2011,2025-06-07 03:05:00,26.5,Laptop,0,3.0,Remote
1491,A01492,U1440,Undergraduate,ECE,R005,Materials Vol.5,Journal,Pearson,2014,2025-02-03 00:04:00,22.4,Mobile,0,NaN,Remote
1492,A01493,U1134,Faculty,Mechanical,R067,Data Science Vol.2,E-Book,NPTEL,2021,2025-07-13 13:37:00,32.9,Mobile,0,4.0,Remote

Shape of Remote Cases: (609, 15)

In [37]:
## 8. Filtering Mobile Device Cases

In [38]:
mobile_cases = df[df["device"] == "Mobile"]
display(mobile_cases)
print("Shape of Mobile Cases:", mobile_cases.shape)

,access_id,user_id,user_type,department,resource_id,resource_title,resource_type,publisher,publication_year,access_datetime,session_minutes,device,downloaded,rating,access_mode
8,A00009,U1099,Faculty,cse,R036,JSTOR Vol.3,Database,McGraw Hill,2010,2025-07-04 12:27:00,27.8,Mobile,0,3.0,Remote
11,A00012,U1063,Faculty,Civil,R070,SpringerLink Vol.1,Database,IEEE,2015,2025-03-16 13:15:00,9.2,Mobile,0,3.0,On-Campus
13,A00014,U1656,Undergraduate,CSE,R023,Finance Vol.2,Journal,Pearson,2005,2025-10-10 11:57:00,34.8,Mobile,0,2.0,On-Campus
14,A00015,U1442,Faculty,CSE,R023,Finance Vol.2,Journal,Pearson,2005,2025-04-08 16:18:00,79.2,Mobile,0,4.0,Remote
16,A00017,U1247,Faculty,CSE,R069,Data Science Vol.2,E-Book,IEEE,2007,2025-03-18 15:13:00,45.2,Mobile,0,5.0,On-Campus
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1488,A01489,U1697,Undergraduate,Management,R003,JSTOR Vol.4,Database,Pearson,2007,2025-09-01 16:26:00,7.9,Mobile,1,3.0,On-Campus
1491,A01492,U1440,Undergraduate,ECE,R005,Materials Vol.5,Journal,Pearson,2014,2025-02-03 00:04:00,22.4,Mobile,0,NaN,Remote
1492,A01493,U1134,Faculty,Mechanical,R067,Data Science Vol.2,E-Book,NPTEL,2021,2025-07-13 13:37:00,32.9,Mobile,0,4.0,Remote
1493,A01494,U1418,Postgraduate,Mechanical,R024,Chemistry Vol.2,Journal,IEEE,2013,2025-02-07 13:25:00,999.0,Mobile,1,1.0,On-Campus
1496,A01497,U1055,Researcher,CSE,R070,SpringerLink Vol.1,Database,IEEE,2015,2025-11-02 21:05:00,25.7,Mobile,0,5.0,On-Campus

Shape of Mobile Cases: (543, 15)

In [39]:
## 9. Filtering Faculty Usage

In [41]:
faculty_cases = df[df["user_type"] == "Faculty"]
display(faculty_cases)
print("Number of faculty_cases: ", faculty_cases.shape)

,access_id,user_id,user_type,department,resource_id,resource_title,resource_type,publisher,publication_year,access_datetime,session_minutes,device,downloaded,rating,access_mode
2,A00003,U1015,Faculty,Civil,R023,Finance Vol.2,Journal,Pearson,2005,2025-01-27 07:54:00,60.3,Campus PC,0,5.0,Remote
5,A00006,U1026,Faculty,Mechanical,R070,SpringerLink Vol.1,Database,IEEE,2015,2025-09-26 01:14:00,12.1,Campus PC,1,2.0,Remote
8,A00009,U1099,Faculty,cse,R036,JSTOR Vol.3,Database,McGraw Hill,2010,2025-07-04 12:27:00,27.8,Mobile,0,3.0,Remote
11,A00012,U1063,Faculty,Civil,R070,SpringerLink Vol.1,Database,IEEE,2015,2025-03-16 13:15:00,9.2,Mobile,0,3.0,On-Campus
14,A00015,U1442,Faculty,CSE,R023,Finance Vol.2,Journal,Pearson,2005,2025-04-08 16:18:00,79.2,Mobile,0,4.0,Remote
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1470,A01471,U1575,Faculty,Sciences,R068,PhD Thesis Vol.3,Thesis,Wiley,2008,2025-04-18 18:39:00,30.3,Campus PC,0,4.0,Remote
1481,A01482,U1678,Faculty,CSE,R022,Scopus Vol.4,Database,Pearson,2016,2025-10-03 07:54:00,42.6,Laptop,0,4.0,Remote
1489,A01490,U1221,Faculty,CSE,R038,Marketing Vol.2,E-Book,Taylor & Francis,2017,2025-07-11 23:21:00,16.4,Laptop,0,5.0,On-Campus
1492,A01493,U1134,Faculty,Mechanical,R067,Data Science Vol.2,E-Book,NPTEL,2021,2025-07-13 13:37:00,32.9,Mobile,0,4.0,Remote
1495,A01496,U1038,Faculty,Management,R067,Data Science Vol.2,E-Book,NPTEL,2021,2025-02-14 21:40:00,10.8,Campus PC,0,4.0,On-Campus

Number of faculty_cases:  (174, 15)

In [40]:
## 10. Filtering Highly Rated Resources

In [45]:
high_rated = df[df["rating"] >= 4]
display(high_rated)
print("Number of high rated accesses: ", high_rated.shape)

,access_id,user_id,user_type,department,resource_id,resource_title,resource_type,publisher,publication_year,access_datetime,session_minutes,device,downloaded,rating,access_mode
0,A00001,U1675,Undergraduate,Mechanical,R070,SpringerLink Vol.1,Database,IEEE,2015,2025-03-19 23:30:00,33.6,Laptop,0,4.0,Remote
1,A00002,U1448,Undergraduate,ECE,R068,PhD Thesis Vol.3,Thesis,Wiley,2008,2025-03-26 14:18:00,26.9,Laptop,1,4.0,Remote
2,A00003,U1015,Faculty,Civil,R023,Finance Vol.2,Journal,Pearson,2005,2025-01-27 07:54:00,60.3,Campus PC,0,5.0,Remote
4,A00005,U1298,Postgraduate,Sciences,R056,Signal Processing Vol.5,Journal,Wiley,2021,2025-09-20 11:53:00,8.0,Laptop,0,4.0,Remote
6,A00007,U1117,Postgraduate,CSE,R055,Data Science Vol.1,E-Book,Springer,2016,2025-10-23 08:50:00,37.2,Laptop,1,5.0,On-Campus
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1495,A01496,U1038,Faculty,Management,R067,Data Science Vol.2,E-Book,NPTEL,2021,2025-02-14 21:40:00,10.8,Campus PC,0,4.0,On-Campus
1496,A01497,U1055,Researcher,CSE,R070,SpringerLink Vol.1,Database,IEEE,2015,2025-11-02 21:05:00,25.7,Mobile,0,5.0,On-Campus
1497,A01498,U1003,Undergraduate,Management,R021,JSTOR Vol.3,Database,Taylor & Francis,2016,2025-04-28 09:50:00,49.8,Laptop,1,5.0,On-Campus
1498,A01499,U1399,Postgraduate,Civil,R049,Finance Vol.2,Journal,NPTEL,2011,2025-04-14 14:29:00,44.4,Laptop,0,5.0,On-Campus
1499,A01500,U1040,Postgraduate,Sciences,R067,Data Science Vol.2,E-Book,NPTEL,2021,2025-04-28 19:33:00,114.5,Laptop,1,4.0,On-Campus

Number of high rated accesses:  (912, 15)

In [44]:
## 11. Filtering CSE Department Cases

In [43]:
cse_cases = df[df["department"] == "CSE"]
display(cse_cases)
print("Number of cse_cases : ", cse_cases.shape)

,access_id,user_id,user_type,department,resource_id,resource_title,resource_type,publisher,publication_year,access_datetime,session_minutes,device,downloaded,rating,access_mode
6,A00007,U1117,Postgraduate,CSE,R055,Data Science Vol.1,E-Book,Springer,2016,2025-10-23 08:50:00,37.2,Laptop,1,5.0,On-Campus
12,A00013,U1178,Postgraduate,CSE,R042,Finance Vol.1,Journal,Springer,2015,2025-11-09 20:54:00,12.7,Laptop,0,3.0,Remote
13,A00014,U1656,Undergraduate,CSE,R023,Finance Vol.2,Journal,Pearson,2005,2025-10-10 11:57:00,34.8,Mobile,0,2.0,On-Campus
14,A00015,U1442,Faculty,CSE,R023,Finance Vol.2,Journal,Pearson,2005,2025-04-08 16:18:00,79.2,Mobile,0,4.0,Remote
16,A00017,U1247,Faculty,CSE,R069,Data Science Vol.2,E-Book,IEEE,2007,2025-03-18 15:13:00,45.2,Mobile,0,5.0,On-Campus
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1472,A00014,U1656,Undergraduate,CSE,R023,Finance Vol.2,Journal,Pearson,2005,2025-10-10 11:57:00,34.8,Mobile,0,2.0,On-Campus
1474,A01475,U1609,Postgraduate,CSE,R034,PhD Thesis Vol.5,Thesis,Wiley,2019,2025-03-19 06:09:00,5.5,Mobile,1,5.0,On-Campus
1481,A01482,U1678,Faculty,CSE,R022,Scopus Vol.4,Database,Pearson,2016,2025-10-03 07:54:00,42.6,Laptop,0,4.0,Remote
1489,A01490,U1221,Faculty,CSE,R038,Marketing Vol.2,E-Book,Taylor & Francis,2017,2025-07-11 23:21:00,16.4,Laptop,0,5.0,On-Campus
1496,A01497,U1055,Researcher,CSE,R070,SpringerLink Vol.1,Database,IEEE,2015,2025-11-02 21:05:00,25.7,Mobile,0,5.0,On-Campus

Number of cse_cases :  (265, 15)

In [42]:
# Filtering Cases with Rating Information

In [ ]:
rated_cases = df[df["rating"].notna()]

display(rated_cases)
print("Shape of Rated Cases:", rated_cases.shape)